### PR TITLE
Improve sound quality

### PR DESCRIPTION
**Pull request by sebdel**
Write registers a bit faster (maybe), but most importantly, fix the R13 enveloppe reset bug. -> Tao songs sound way better.

### CODE REVIEW

**Comment by FlorentFlament** [comment]
Hi Sebdel,

Thanks for the PR ! I'm sorry I didn't see you pull request earlier (github misconfiguration of mine). You may be right about the enveloppe reset issue, I'd have to do some tests.

Though, This looks like a complete rewrite of this little project (by replacing 47 lines by 1270 lines of code ; ). Not that I'm against refactoring, but I kind of prefer keeping this project simple for now (no offense). Also, I'll have a look at your digidrum support !

Best regards

**Comment by sebdel** [comment]
Sorry about that, I don't know what I was thinking, it's been a while ;)

If there is *one* thing to retain from this PR: You should not rewrite to register 13 when its value doesn't change as it resets the envelope and mess up with a lot of songs.

BR
Seb

**Comment by FlorentFlament** [comment]
No problem ; )

Ok, sounds reasonable. Do you have some names of tunes that sound better when we don't mess with the envelope reset, so that I could do some tests ?

**Comment by sebdel** [comment]
Cuddly demos main menu by Mad Max. It's especially obvious in this one.

**Comment by FlorentFlament** [comment]
Thanks !

Indeed, the envelope register kills this tune. Though from what I understand, even when the register value isn't 0xff, writing in the 'envelope shape control' register resets the envelope (http://www.ym2149.com/ym2149.pdf). And since the YM format captures the 'content' of the registers every 1/50th second, but not whether it has been written to or not, I don't think the YM format can handle the 'envelope shape control' feature properly. I completely disabled writing in this register in my latest commit.

Ah, I also added your `serial-setup.sh`. Thanks again

**Comment by simondotm** [comment]
I interpreted the YM file format specs to mean that only when R13 is not 0xff should it be sent to the chip?

> As we've seen, r13 has a particular status. If the value stored in the file is 0xff, YM emulator will not reset the waveform position.

**Comment by FlorentFlament** [comment]
@simondotm Actually, I think you are right. I happen to had a quick look at the ST-Sound code ( http://leonard.oxg.free.fr/stsound_download.html ) and there is indeed a special case for this R13 register, which is skipped when its value in the YM file is 0xff ( YmMusic.cpp line 435 ). Which, as you pointed out is documented in https://github.com/skeezix/zikzak/blob/master/zik80/audio-gen/ym-file-format.txt , but not in the official documentation of Leonard: http://leonard.oxg.free.fr/ymformat.html .. I'll do an update soon.

**Pull request closed without merging**
